# Change these first
owner: hoangsvit # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: ePlus.DEV
    url: https://eplus.dev
    
  - name: ePlus Radio
    url: https://radio.eplus.dev

  - name: Xe
    url: https://xe.eplus.dev
    
  - name: ePlus News
    url: https://news.eplus.dev

  - name: ePlus - Top GitHub Users
    url: https://top-github-users.eplus.dev

  - name: ePlus - Top GitHub
    url: https://top-github.eplus.dev

  - name: ePlus - Free For Dev
    url: https://free-for-dev.eplus.dev
    
  - name: Graphql Studio
    url: https://graphql-studio.eplus.dev
    
  - name: ePlus Analytics
    url: https://analytics.eplus.dev
    
  - name: ePlus JSON Crack 
    url: https://json.eplus.dev

  - name: ePlus JSON Crack Plus
    url: https://jsoncrack.eplus.dev
    
  - name: ePlus Cors Anywhere
    url: https://cors-anywhere.eplus.dev
    icon: https://cdn.jsdelivr.net/gh/ePlus-DEV/cdn.eplus.dev/img/icon/right-left-duotone.png

  - name: ePlus AirDrop
    url: https://air.eplus.dev
    icon: https://cdn.jsdelivr.net/gh/ePlus-DEV/cdn.eplus.dev/img/icon/airdrop.png
    
  - name: Hỗ trợ hệ thống MWG
    url: https://mwg.eplus.dev

  - name: ePlus Top GitHub Users
    url: https://top-github-users.eplus.dev
    
  - name: ePlus ZingMP3
    url: https://zing.eplus.dev

  - name: ePlus DEV Tools
    url: https://tools.eplus.dev

  - name: ePlus Markdown
    url: https://markdown.eplus.dev

  - name: ePlus Draw
    url: https://draw.eplus.dev

  - name: ePlus Dashboard
    url: https://dashboard.eplus.dev

  - name: ePlus CDN
    url: https://cdn.eplus.dev

  - name: ePlus Blog (Blogger)
    url: https://blog.eplus.dev

  - name: ePlus Laravel Artisan
    url: https://artisan.eplus.dev
  
  - name: ePlus updown
    url: https://updown.eplus.dev

  - name: ePlus Portfolio
    url: https://portfolio.eplus.dev
    icon: https://assets-global.website-files.com/6540c35344425ec153655b43/6540c35444425ec153655bee_favicon-dashflow-webflow-template.svg

  - name: ePlus Mailpit
    url: https://mailpit.eplus.dev
    icon: https://cdn.jsdelivr.net/gh/ePlus-DEV/cdn.eplus.dev/assets/subdomain/mailpit/favicon.svg
    
  - name: ePlus HUB
    url: https://hub.eplus.dev
    
  - name: ePlus Uptime
    url: https://uptime.eplus.dev
    
  - name: ePlus Status
    url: https://status.eplus.dev
    
  - name: ePlus Show Code
    url: https://code.eplus.dev

  - name: ePlus Cronjob
    url: https://cronjob.eplus.dev

  - name: ePlus Drawd DB
    url: https://drawdb.eplus.dev

  - name: ePlus TimeSheet
    url: https://timesheet.eplus.dev

  - name: ePlus Metrics
    url: https://metrics.eplus.dev
    icon: https://cdn.jsdelivr.net/gh/ePlus-DEV/cdn.eplus.dev/assets/subdomain/metrics/favicon.ico
    
  - name: ePlus Radio (old)
    url: https://old-radio.eplus.dev
    
  - name: David ❤️ Sam (Backup)
    url: https://dev-david-sam.pantheonsite.io
    
  - name: 🍄 Nấm Nông Lâm
    url: https://namnonglam.edu.vn
    
  - name: Laravel 10x on Render
    url: https://laravel-10x.onrender.com
    icon: https://cdn.jsdelivr.net/gh/ePlus-DEV/cdn.eplus.dev/img/icon/render-favicon-32x32.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.eplus.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/hoangsvit/uptime/master/assets/upptime-icon.svg
  name: Uptime
  introTitle: "**Uptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/hoangsvit/uptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/hoangsvit/uptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  scripts:
    - src: https://www.googletagmanager.com/gtag/js?id=G-FQ4NLQRFXF
      async: true
  js: "window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-FQ4NLQRFXF');"

commitMessages:
  commitAuthorName: "Uptime Bot"
  commitAuthorEmail: "contact@eplus.dev"

i18n:
  footer: Made with ❤️ by [ePlus.DEV](https://eplus.dev)

workflowSchedule:
  graphs: "*/30 * * * *"
  responseTime: "0 23 * * *"
  staticSite: "*/30 * * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 0 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
